[package]
name = "kifuwarabe_shogi2018"
version = "0.1.0"
authors = ["muzudho <muzudho1@gmail.com>"]

[dependencies]
rand="0.3.0"
lazy_static = "1.1.0"

[dependencies.kifuwarabe_shell]
git = "https://github.com/muzudho/rust_kifuwarabe_shell.git"
rev = "6deac338e5ad49992f2f7bfe94c9415bf8382a26"

[dependencies.kifuwarabe_usi]
git = "https://github.com/muzudho/rust_kifuwarabe_usi.git"
rev = "f0be3fabdcc0eafc525101048e55b91b516052b6"

[dependencies.kifuwarabe_position]
git = "https://github.com/muzudho/rust_kifuwarabe_position.git"
rev = "8956e8b019be11e85ac4fee4d75b7602d5e7fc21"

[dependencies.kifuwarabe_movement]
git = "https://github.com/muzudho/rust_kifuwarabe_movement.git"
rev = "83cd4adec44675600a075401a1d0b6f3297044c2"

[dependencies.kifuwarabe_alpha_beta_search]
git = "https://github.com/muzudho/rust_kifuwarabe_alpha_beta_search.git"
rev = "2a1bdbaadd461a62afca91de3d99d88954c3e67b"
