[package]
name = "kifuwarabe_shogi2018"
version = "0.1.0"
authors = ["muzudho <muzudho1@gmail.com>"]

[dependencies]
rand="0.3.0"
lazy_static = "1.1.0"

[dependencies.kifuwarabe_shell]
git = "https://github.com/muzudho/rust_kifuwarabe_shell.git"
rev = "6deac338e5ad49992f2f7bfe94c9415bf8382a26"

[dependencies.kifuwarabe_usi]
git = "https://github.com/muzudho/rust_kifuwarabe_usi.git"
rev = "096ebbb384319a74b831ba5405b723ae4f26071d"

[dependencies.kifuwarabe_position]
git = "https://github.com/muzudho/rust_kifuwarabe_position.git"
rev = "39c301ced1f093585412da49068100e114dc0a30"

[dependencies.kifuwarabe_movement]
git = "https://github.com/muzudho/rust_kifuwarabe_movement.git"
rev = "dd323dac889f299ba721f3cf788056e4f7a8a0f7"

[dependencies.kifuwarabe_alpha_beta_search]
git = "https://github.com/muzudho/rust_kifuwarabe_alpha_beta_search.git"
rev = "d6e4b3396b632b66a1ed5e652e8a75c17f8b78f9"
